version: "3.6"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  shop-api:
    image: shop-api
    container_name: shop-api
    ports:
      - 8080:8080
    depends_on:
      - kafka
  shop-validator:
    image: shop-validator
    container_name: shop-validator
    ports:
      - 8081:8080
    depends_on:
      - kafka
  shop-report:
    image: shop-report
    container_name: shop-report
    ports:
      - 8082:8081
    depends_on:
      - kafka