create table shop (
    id bigint generated by default as identity,
    buyer_identifier varchar(100) not null,
    identifier varchar not null,
    status varchar not null,
    date_shop date,
    primary key (id)
);

create table shop_item (
    id bigint generated by default as identity,
    product_identifier varchar(100) not null,
    amount int not null,
    price float not null,
    shop_id bigint REFERENCES shop(id),
    primary key (id)
);